#!/usr/bin/bash
#shellcheck source=/dev/null

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export COMMON_SHELL_PROFILE_DIR="$XDG_CONFIG_HOME/shell"
export SPEC_SHELL_PROFILE="$HOME/.bashrc"
source "$COMMON_SHELL_PROFILE_DIR/profile.sh"

# x-cmd
[ ! -f "$HOME/.x-cmd.root/X" ] || . "$HOME/.x-cmd.root/X" # boot up x-cmd.
# xlings
test -f "$HOME/.xlings/config/shell/xlings-profile.sh" && source "$HOME/.xlings/config/shell/xlings-profile.sh"
