#!/usr/bin/bash

# GitHub Clone
# 用法: ghc <repo_name> [options]...

if [ $# -eq 0 ]; then
    echo "Usage: ghc <repo_name> [options]..."
    exit 1
fi

repo_name=$1
git_args=("${@:2}")

repo_name="${repo_name#"https://github.com/"}"
repo_name="${repo_name#"http://github.com/"}"
repo_name="${repo_name#"git@github.com:"}"

repo_name="${repo_name%".git"}"

git clone "git@github.com:$repo_name.git" "${git_args[@]}"
