#!/usr/bin/bash

# GitHub Clone
# 用法: ghc <repo_name> [options]...

if [ $# -eq 0 ]; then
    echo "Usage: ghc <repo_name> [options]..."
    exit 1
fi

repo_name=$1
git_args=("${@:2}")

repo_name="${repo_name#"https://github.com/"}"
repo_name="${repo_name#"http://github.com/"}"
repo_name="${repo_name#"git@github.com:"}"

repo_name="${repo_name%".git"}"

if command -v gh >/dev/null 2>&1; then
    gh repo clone "$repo_name" -- "${git_args[@]}"
    exit $?
fi

if command -v git >/dev/null 2>&1; then
    git clone "git@github.com:$repo_name.git" "${git_args[@]}"
    exit $?
fi

echo "Error: Neither 'gh' nor 'git' command is available. Please install one of them to clone the repository."
exit 1
