#!/usr/bin/bash
# shellcheck disable=SC2086

# 依赖: fzf
# 环境:
#   $QUERY_ARG  := "-Qq"
#   $INFO_ARG   := "-Qi"
#   $FZF_ARGS   += ("--query" "$2")
#   $AUR_HELPER := "yay"

# 用法: yc <option> [query]
# yay 列出本地安装的所有软件包 并执行 <option>

# 如 yc -R linux 会打开 fzf 界面 并设置初始查询词为 linux
# 选定 linux-lts 后 执行 yay -R linux-lts

# 环境变量使用示例: 查询所有软件包 (包括未安装 不包括 AUR)
# QUERY_ARG=-SNlq INFO_ARG=-Si yc

[ -z "$QUERY_ARG" ] && QUERY_ARG="-Qq"
[ -z "$INFO_ARG" ] && INFO_ARG="-Qi"

[ -n "$2" ] && FZF_ARGS+=("--query" "$2")

if [ -z "$PM" ]; then
    command -v yay > /dev/null 2>&1 && PM="yay"
    command -v paru > /dev/null 2>&1 && PM="paru"
    command -v pacman > /dev/null 2>&1 && PM="pacman"
fi

if [ -z "$PM" ]; then
    echo "Error: 没有找到任何 AUR Helper 或 pacman" >&2
    exit 1
fi

PREVIEW_CMD="""
    $PM -Qs --color=always \"^\\\$0\\\$\"
    echo
    $PM $INFO_ARG --color=always \"\\\$0\"
"""


r="$($PM $QUERY_ARG | fzf \
    --multi \
    "${FZF_ARGS[@]}" \
    --preview "bash -c \"$PREVIEW_CMD\" {}"
)"
[ -z "$r" ] && exit 0

$PM $1 $r
