# Mpv

vo = gpu-next
gpu-api = vulkan
#gpu-context = waylandvk

hwdec = auto

# 打开时最大化窗口
window-maximized = yes

# 播放完成后保持打开
#keep-open = yes

# 禁用内置 stats.lua 脚本 (使用已翻译的 scripts/stats.lua 脚本)
load-stats-overlay = no

# HDR
target-colorspace-hint = yes
