#!/hint/bash
# shellcheck disable=all

--ro-bind-try ${HOME}/图片/屏幕截图 ${HOME}/图片/屏幕截图
--ro-bind-try ${HOME}/视频/OBS ${HOME}/视频/OBS

# --bind ${HOME}/公共/qwq ${HOME}/公共/qwq
# --setenv LD_PRELOAD ${HOME}/公共/qwq/libqwqnt_core.so
