# uosc 配置文件

# 本地化语言优先级从高到低
# 也控制 `download-subtitles` 菜单获取的语言
# 内置语言可在 `uosc/intl` 中找到
# `slang` 是一个关键字，用于继承 `--slang` mpv 配置的值
# 支持自定义 json 文件路径：`languages=~~/custom.json,slang,en`
languages=slang,zh-hans,en
